### ISSUE TITLE
Record only answred calls

### ISSUE THREAD

**Issue by guilhas** [riul88/call-recorder-for-android#19]
Hello,

Is it possible to record only answred calls?

Best regards,
Guilherme Lino

**Comment by GreenLunar** [comment]
No, as far as I can see.

**Comment by guilhas** [comment]
Thank you

**Comment by GreenLunar** [comment]
Why did you close this issue?

**Comment by guilhas** [comment]
It is only possible Android 5+

https://stackoverflow.com/questions/13134331/cannot-detect-when-outgoing-call-is-answered-in-android
